### ISSUE TITLE
期望新的功能

### ISSUE THREAD

**Issue by detail-c** [ec50n9/MsgAttach-Watcher#1]
首先非常感谢ec50n9，提供方便的工具。在使用体验以后，能期待2个功能么：
1、在添加白名单界面搜索框，输入关键词后显示的关键词，左侧能否添加一个全选/全不选（目前是有勾选选择框）
![image](https://github.com/ec50n9/MsgAttach-Watcher/assets/46638805/5cc69ee0-46df-4dce-8cb7-99c1be986705)
![image](https://github.com/ec50n9/MsgAttach-Watcher/assets/46638805/b8da2cd3-7988-43e8-a984-35089b2c65ad)
2、依然是在这个加白名单界面，可否添加一键导出当前界面的信息的excel文件（其实也就是一键导出当前微信的好友及群聊），标题就按照界面显示的字段。
期待你的更新ec50n9！！！感谢您的无私开源！！！！

**Comment by ec50n9** [comment]
哈哈！很高兴收到你的反馈，对于列表的全选/全不选/反选操作已经开发完成，但还没时间打包，可自行拉去最新代码来自行打包哦。关于好友数据导出的功能我还在考虑是否应该新加一个tab页面专门存放一些跟“图片监听”不相关但又有需要的功能。如果有进展，我会在这里通知你，再次感谢你的反馈！

**Comment by detail-c** [comment]
> 哈哈！很高兴收到你的反馈，对于列表的全选/全不选/反选操作已经开发完成，但还没有时间，可以自行备份去从行拉备份的最新代码哦。关于好友数据恢复的功能我还在考虑是否应该新加一个选项卡页面专门放置一些跟“图片监听”不相关但又需要的功能。如果有进展，我会在这里通知你，再次感谢你的反馈！

好的，ec50n9！非常感谢您的开发！十分感谢！

**Comment by ec50n9** [comment]
晚上好，好友列表导出的功能也加上啦，它在这里：
![image](https://github.com/ec50n9/MsgAttach-Watcher/assets/30485326/b798e1f6-c112-47a1-b5a9-713475cd9248)

新版的代码也已经打包并发布了releases，有时间的话可以下载更新一下哦

**Comment by detail-c** [comment]
![image](https://github.com/ec50n9/MsgAttach-Watcher/assets/46638805/646f23ba-f5eb-4a7a-b044-a163d454fbef)
在使用工具-导出时，报clever cannot be used in worksheets错误
网上看了一下，https://zhuanlan.zhihu.com/p/673225408，但别人换了xlsxwriter写excel解决的，你使用的openpyxl。
我感觉是写入的数据中可能包含Excel工作表不允许的字符，因为好友，总要特殊字符。

**Comment by ec50n9** [comment]
收到，我本地导出的时候没有遇到过这个问题，我刚刚补充了非法字符转换的步骤：

![image](https://github.com/ec50n9/MsgAttach-Watcher/assets/30485326/f78e4c69-c0d6-4d05-b6de-3c77c8b4ae94)

但我不清楚它是否真的有效，代码已经更新了，如果可以的话，麻烦你尝试一下直接运行python代码的方式来启动程序并进行导出测试，代码的运行方式我已经补充到README中啦。

如果它仍然报错的话，尽可能把更详细的错误或者把错误的字符复制给我调试一下。

**Comment by detail-c** [comment]
> 收到，我本地导出的时候没有遇到过这个问题，我刚刚补充了非法字符转换的步骤：
> 
> ![image](https://private-user-images.githubusercontent.com/30485326/331759050-f78e4c69-c0d6-4d05-b6de-3c77c8b4ae94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjI4ODcsIm5iZiI6MTcxNjU2MjU4NywicGF0aCI6Ii8zMDQ4NTMyNi8zMzE3NTkwNTAtZjc4ZTRjNjktYzBkNi00ZDA1LWI2ZGUtM2M3N2M4YjRhZTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNGM0MjE4NmZhYTk3NzQ3YjBlMjRhNzJmYTViNWY5ZmMyYjkwMWM1MDI5ZGNjMWExNWU0NzAwOWZmNDA0YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7uPsEyYbjxtOQK58sLSdT8g7myOJW05G9nvxc9Fs-HE)
> 
> 但我不清楚它是否真的有效，代码已经更新了，如果可以的话，麻烦你尝试一下直接运行python代码的方式来启动程序并进行导出测试，代码的运行方式我已经补充到README中啦。
> 
> 如果它仍然报错的话，尽可能把更详细的错误或者把错误的字符复制给我调试一下。

sorry，ec50n9!上周比较忙，有收到你的邮件反馈，但一直没有测试，非常的抱歉，刚刚测试了一下，导出是成功的。
![image](https://github.com/ec50n9/MsgAttach-Watcher/assets/46638805/3aa4223c-606f-4053-8d2f-3bdc14c16cf2)
但貌似打开excel文件后，会提示这个：
![image](https://github.com/ec50n9/MsgAttach-Watcher/assets/46638805/2987fcf4-c1bf-41d2-8e52-21837d009bc8)
但是excel会自动修复，并移除公式，目前测试是正常导出了，非常感谢您的开源及功能的更新，伟大的ec50n9！

本地测试运行过程中遇到的报错（仅参考）：
错误：from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto'
解决方法：关于Module Not Found Error No module named Crypto解决（原创：https://blog.csdn.net/Ghjkku/article/details/138223601    ）
运行以下
```
pip uninstall crypto
pip uninstall pycryptodome
pip install pycryptodome
```
原因可能之一：
知其然知其所以然
_首先你要知道 导入的这个模块中的AES是在pycryptodome这个库里面的,所以 crypto这个库对你来说是没用的。
而如果你装了crypto 这个库, 这两个库会安装到同一个文件夹, 然后本应该 Crypto 这个大写的文件夹变成小写 crypto(因为windows本身不区分大小写), 这样就会导致找不到这个模块, 两个库的名字发生冲突。
另外看到很多文章解决办法是: 改文件夹名字, 将小写c改为大写C, 这样虽然也能解决, 但不是问题的根本原因, 根本原因就是 windows 不区分大小写, 所以卸载无用的库是最好的解决办法!_
